library(sqldf)
data <- read.csv.sql("household_power_consumption.txt",sql="select * from file where Date in ('1/2/2007','2/2/2007')" , header=TRUE, sep=";")
data$DateTime <- strptime(paste(data$Date, data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
plot(x=data$DateTime,y=data$Sub_metering_1, type="n",xlab="", ylab="Energy sub metering")
lines(x=data$DateTime,y=data$Sub_metering_1 )
lines(x=data$DateTime,y=data$Sub_metering_2, col = "red")
lines(x=data$DateTime,y=data$Sub_metering_3, col = "blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"),col=c("black", "red","blue"),lty=1)

dev.print(device = png, filename = 'plot3.png', width = 480, height = 480)
dev.off()