library(sqldf)
data <- read.csv.sql("household_power_consumption.txt",sql="select * from file where Date in ('1/2/2007','2/2/2007')" , header=TRUE, sep=";")
data$DateTime <- strptime(paste(data$Date, data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
plot(x=data$DateTime,y=data$Global_active_power, type="l",xlab="", ylab="Global Active Power (kilowatts)")
dev.print(device = png, filename = 'plot2.png', width = 480, height = 480)
dev.off()